input_list: "some_plasmids.txt" #list of plasmid fasta files

output_dir: "out" #output directory

chr_to_plasmid: "chr_to_plasmid.tsv" #tsv which relates plasmid IDs to chromosomal IDs

host_tree: "host_tree.nw" #chromosomal tree for determining relevant host clades, in Newick format

dcj-indel: 4

containment: 0.5

big_subcomm_size: 10

ggcallaroo: "/path/to/ggcallaroo"

bakta_db: "/path/to/bakta_db"